### ISSUE TITLE
Pass only host to applescript

### ISSUE THREAD

**Issue by otakustay** [ExiaSR/better-opn#11]
Current implement of `better-opn` passes the entire url to `openChrome.applescript` to match an opened tab.

In some cases, when we debugging a web application, we navigate between urls and finally stay on another url that does not match the one passed to applescript.

This can especially happen when we set a specified url with some long pathname to `better-opn`, in our case it is `host.com/login` to ensure developers signed in first, but after that the url becomes `host.com/some-module` and cannot be matched against `host.com/login`.

We'd like to see an option to "loosely determine which tab to reuse" by passing only `host.com` to applescript.

**Comment by ExiaSR** [comment]
@otakustay I think this is a legit use case.

Since this is a new behaviour, users should opt-in to use this new feature.

Regrading configuration, for the sake of keeping the interface consistent with `open`, instead of adding a new attribute to `options`, we can use an environment variable to control this behaviour, i.e

```js
// open.js
require('better-opn')('http://localhost:3000/login')
```

```bash
$ OPEN_MATCH_HOST_ONLY=true node open.js
```

Are you opened to contribute?
