### ISSUE TITLE
How to get the opt configuration document ?

### ISSUE THREAD

**Issue by CGerAJ** [ExiaSR/better-opn#3]
https://github.com/ExiaSR/better-opn/blob/c5d60ea88ba1f000f3bbc8fbbc0e97be239bb47b/src/index.js#L29

I hope I can not refresh the current tab page, tks~

**Comment by ExiaSR** [comment]
Hi, 

I’m not sure I understand your question (feel free to rephrase your question in Chinese)

I suppose you’re looking for the documentation of the ‘opts’ object. It is intended to pass down to the “open” library (formerly known as “opn”) when launching with AppleScript doesn’t work out. 

https://github.com/ExiaSR/better-opn/blob/master/src/index.js#L67

Please refer to their docs https://www.npmjs.com/package/open

**Comment by CGerAJ** [comment]
使用场景
当我使用nodemon的时候 每次会自动刷新当前tab 我不希望刷新 不知道有没有配置项可以禁用自动刷新？

**Comment by CGerAJ** [comment]
https://github.com/ExiaSR/better-opn/blob/c5d60ea88ba1f000f3bbc8fbbc0e97be239bb47b/src/index.js#L43

我想我也许想修改的是这个object

**Comment by ExiaSR** [comment]
> https://github.com/ExiaSR/better-opn/blob/c5d60ea88ba1f000f3bbc8fbbc0e97be239bb47b/src/index.js#L43
> 
> 我想我也许想修改的是这个object

@CGerAJ 

Because `tab reloading` is controlled by `AppleScript`, there is no easy way to do customization from JS unless we include an additional `AppleScript` to achieve such behaviour in the release.

I believe the ideal solution for your use case is to make `path` to the `AppleScript` configurable, then you may customize the behaviour as you wish.

### Implementation
```js

const startBrowserProcess = (browser, url, opts = { pathToAppleScript: '../openChrome.applescript' }) {

    // ...

    execSync(`osascript ${opts.pathToAppleScript} "${encodeURI(url)}"`)

    // remove `pathToAppleScript` from `opts` before fallback to `open`
}
```

### Usage
```js
const opn = require('better-opn')

open('https://localhost:3000', { pathToAppleScript: 'full_path_to_custom_applescript' })
```

Feel free to open a PR if this meets your needs.

**Comment by CGerAJ** [comment]
非常感谢您的建议  我需要查阅一下文档，再考虑如何开始～ 有时间我研究一下 谢谢～
